language: node_js
sudo: false
node_js:
- '0.12'
env: APPC_ENV=development
before_script:
- npm cache clean
- npm install -g grunt-cli
script:
- npm test
- grunt cover
before_install:
- openssl aes-256-cbc -K $encrypted_966551a5d772_key -iv $encrypted_966551a5d772_iv
 -in development.js.enc -out test/conf/development.js -d
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: K18mPmHWVnAXONheZ1u6XO+FdaK9ZKWvuPgGmV4bJmyP+t77Hgpdwh4m7MBxpAsQ2uU8nuaV8MrQpG+vfNv6WQLlulUewgA3jHI5QgJC639GTGVg2U3IyRfPOzn+/1A7aEeOLNyRcRhjRuycKdarys/nJ+O+VZVQVJdtthOG3io=
  on:
    tags: true
    repo: appcelerator/appc-platform-sdk