language: node_js
sudo: true
node_js:
- '0.12'
env: APPC_ENV=development
before_script:
- npm cache clean
- npm install -g grunt-cli
script:
- npm test
- grunt cover
before_install:
- openssl aes-256-cbc -K $encrypted_966551a5d772_key -iv $encrypted_966551a5d772_iv
 -in development.js.enc -out test/conf/development.js -d